# This is a basic workflow to help you get started with Actions

name: Building Ch02 notebook

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      LABS:
        description: 'Labs version'
        required: true
        default: 'v2'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install
      - name: Install dependencies 
        run: |
          pip install .

      # Runs a set of commands using the runners shell
      - name: Build notebook for Ch02 (some errors, not really a test)
        env:
          LABS:  ${{ inputs.LABS }}
        run: |
          git clone https://github.com/intro-stat-learning/ISLP_labs.git
          cd ISLP_labs
          git checkout $LABS
          jupyter nbconvert --execute --inplace Ch02-statlearn-lab.ipynb --allow-errors 

      - name: 'Upload Ch02 lab'
          uses: actions/upload-artifact@v3
          with:
            name: Ch02-statlearn-lab
            path: Ch02-statlearn-lab.ipynb
            retention-days: 5